
baseURL = "https://airflowsummit.org/"
title = "Airflow Summit"
description = "Airflow summit is the premier conference for the worldwide community of developers and users of Apache Airflow."
enableRobotsTXT = true
RemovePathAccents = true
DefaultContentLanguage = "en"

theme = "airflowsummit"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "About"
  URL = "/about"
  weight = 1


#[[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about"
#    weight = 1
#  [[menu.main]]
#    identifier = "about1"
#    name = "About"
#    url = "/about"
#    parent = "about"
#    weight = 1
#  [[menu.main]]
#    identifier = "about2"
#    name = "Partner With Us"
#    url = "/partner-with-us"
#    parent = "about"
#    weight = 2

  #[[menu.main]]
  #  identifier = "category"
  #  name = "Program"
  #  url = "/program"
  #  weight = 1
  #[[menu.main]]
  #  identifier = "category1"
  #  name = "Program"
  #  url = "/program"
  #  parent = "category"
  #  weight = 1
  #[[menu.main]]
  #  identifier = "category2"
  #  name = "Panels"
  #  url = "/sessions/2023/panels"
  #  parent = "category"
  #  weight = 2
  #[[menu.main]]
  #  identifier = "category3"
  #  name = "Workshops"
  #  url = "/sessions/2023/workshops"
  #  parent = "category"

  [[menu.main]]
  name = "Speakers"
  URL = "/speakers/archive"
  weight = 3

  #[[menu.main]]
  #name = "Networking"
  #URL = "/networking/"
  #weight = 3

  [[menu.main]]
  name = "Venue"
  URL = "venue"
  weight = 4


  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 7


# Everything below this are Site Params

[params]
description = "Airflow summit is the premier conference for the worldwide community of developers and users of Apache Airflow."
logo = "/images/logo-as2024-2.svg"
home = "Home"
privacy_policy = "/privacy"
google_analytics_4 = "G-DQ3SEJY0LP"
google_ads = "AW-10857785820"

# First one is picked as the Twitter card image if not set on page.
images = ["/images/as2024-cardtmp.jpg"]
start_date = "2023-09-19T09:00-05:00"
end_date = "2023-09-21T17:00-05:00" 

[params.hero]
text = "September 19-21, 2023. Toronto, Canada."

# [params.hero.cta1]
# text = "Submit to our CFP"
# link = "https://sessionize.com/airflow-summit-2024/"

[params.hero.cta1]
text = "Get your ticket"
link = "/tickets"

# Navigation button
[params.navigation_button]
enable = true
label = "Tickets"
link = "/tickets"


[params.links]
[[params.links.media]]
    name = "Email us"
    url = "mailto:info@airflowsummit.org"
    icon = "fa fa-envelope"
[[params.links.media]]
    name = "Follow us on Twitter"
    url = "https://twitter.com/airflowsummit/"
    icon = "fab fa-twitter"
[[params.links.media]]
    name = "Check us on LinkedIn"
    url = "https://www.linkedin.com/company/airflow-summit"
    icon = "fab fa-linkedin-in"
[[params.links.media]]
    name = "Watch us on YouTube"
    url = "https://www.youtube.com/channel/UCSXwxpWZQ7XZ1WL3wqevChA/"
    icon = "fab fa-youtube"
[[params.links.media]]
    name = "Check us on Instagram"
    url = "https://www.instagram.com/airflowsummit/"
    icon = "fab fa-instagram"

[[params.links.footer]]
    name = "Prospectus"
    url = "/docs/AirflowSummit2024-Prospectus-v1_5.pdf"
    target="_blank"
[[params.links.footer]]
    name = "Session archive"
    url = "/sessions"
[[params.links.footer]]
    name = "Speaker archive"
    url = "/speakers/archive/"
[[params.links.footer]]
    name = "Organizers"
    url = "/team"
[[params.links.footer]]
    name = "Code of Conduct"
    url = "/coc"
[[params.links.footer]]
    name = "Accessibility"
    url = "/accessibility"
[[params.links.footer]] 
    name = "Privacy Policy"
    url = "/privacy"
[[params.links.footer]]
    name = "Testimonials"
    url = "/testimonials"


[permalinks]
tags = "/blog/tags/:slug/"
posts = "/:year/:month/:title/"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap.min.css"

[[params.plugins.css]]
link = "/plugins/bootstrap-table.min.css"

[[params.plugins.css]]
link = "/plugins/fontawesome.css"

# JS Plugins
[[params.plugins.js]]
link="/plugins/jquery.min.js"

[[params.plugins.js]]
link="/plugins/bootstrap.bundle.min.js"

[[params.plugins.js]]
link="/plugins/bootstrap-table.min.js"

