
baseURL = "https://airflowsummit.org/"
title = "Airflow Summit"
description = "Airflow summit is the first conference for the worldwide community of developers and users of Apache Airflow."
enableRobotsTXT = true
RemovePathAccents = true
DefaultContentLanguage = "en"
googleAnalytics = "UA-158553455-1"

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = "airflowsummit"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1


  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 7


# Everything below this are Site Params

[params]
description = "Airflow summit is the premier conference for the worldwide community of developers and users of Apache Airflow."
logo = "/images/logo-white.svg"
home = "Home"
privacy_policy = "/privacy"

# First one is picked as the Twitter card image if not set on page.
images = ["/images/card-july.jpg"]
start_date = "2022-05-23T11:00-05:00"
end_date = "2022-05-27T17:00-05:00"

[params.hero]
text = "May 23-27, 2022. Come fly with us."

[params.hero.cta1]
text = "Join our CFP!"
link = "https://sessionize.com/airflow-summit-2022/"
 
#[params.hero.cta2]
#text = ""
#link = ""

# Navigation button
[params.navigation_button]
enable = false
label = "Register"
link = "https://airflowsummit.org/live"


[params.links]
[[params.links.media]]
    name = "Email us"
    url = "mailto:info@airflowsummit.org"
    icon = "fa fa-envelope"
[[params.links.media]]
    name = "Follow us on Twitter"
    url = "https://twitter.com/airflowsummit/"
    icon = "fab fa-twitter"
[[params.links.media]]
    name = "Check us on LinkedIn"
    url = "https://www.linkedin.com/company/airflow-summit"
    icon = "fab fa-linkedin-in"
[[params.links.media]]
    name = "Watch us on YouTube"
    url = "https://www.youtube.com/channel/UCSXwxpWZQ7XZ1WL3wqevChA/"
    icon = "fab fa-youtube"

[[params.links.footer]]
    name = "About"
    url = "about"
[[params.links.footer]]
    name = "Code of Conduct"
    url = "/coc"
[[params.links.footer]]
    name = "Accessibility"
    url = "/accessibility"
[[params.links.footer]] 
    name = "Privacy Policy"
    url = "/privacy"
[[params.links.footer]]
    name = "Organizers"
    url = "/team"
[[params.links.footer]]
    name = "Prospectus"
    url = "/docs/Airflow-Summit-2022.pdf"
    target="_blank"
[[params.links.footer]]
    name = "Call for papers"
    url = "https://sessionize.com/airflow-summit-2022/"
    target="_blank"


[permalinks]
tags = "/blog/tags/:slug/"
posts = "/:year/:month/:title/"

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "/plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"

# JS Plugins
[[params.plugins.js]]
link = "/plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "/plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link="https://kit.fontawesome.com/4a6d2efc2e.js"
[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"
