name: Deploy Hugo site to firebase

on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Fetch Hugo to Firebase docker image
    - uses: softwareguru/hugo-on-fire@master
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
